import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

// Import the real Firebase configuration generated by the setup tool
import firebaseConfig from '../firebase-applet-config.json';

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
// Use the named database ID from the config
const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
const storage = getStorage(app);

export { app, auth, db, storage };
