import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore, doc, getDocFromServer } from "firebase/firestore";
import { getStorage } from "firebase/storage";
import { getDatabase } from "firebase/database";

// Import the real Firebase configuration generated by the setup tool
import firebaseConfigJson from '../firebase-applet-config.json';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || firebaseConfigJson.apiKey,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || firebaseConfigJson.authDomain,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || firebaseConfigJson.projectId,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || firebaseConfigJson.storageBucket,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || firebaseConfigJson.messagingSenderId,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || firebaseConfigJson.appId,
  databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL || `https://${firebaseConfigJson.projectId}-default-rtdb.firebaseio.com`,
};

const databaseId = process.env.NEXT_PUBLIC_FIREBASE_DATABASE_ID || firebaseConfigJson.firestoreDatabaseId;

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
// Use the named database ID from the config
const db = getFirestore(app, databaseId);
const storage = getStorage(app);
const rtdb = getDatabase(app);

// Test connection to Firestore
async function testConnection() {
  if (typeof window === 'undefined') return;
  
  const currentConfig = {
    projectId: firebaseConfig.projectId,
    databaseId: databaseId,
    hasApiKey: !!firebaseConfig.apiKey
  };

  try {
    // Attempt to fetch a non-existent doc from the server to verify config
    await getDocFromServer(doc(db, '_connection_test_', 'ping'));
    console.log("Firestore connected successfully.");
  } catch (error: any) {
    if (error.message?.includes('the client is offline') || error.message?.includes('Could not reach Cloud Firestore backend')) {
      console.error("CRITICAL: Firestore configuration is incorrect or backend is unreachable.");
      console.error("Current Configuration being used:", currentConfig);
      console.error("Troubleshooting steps:");
      console.error("1. Ensure NEXT_PUBLIC_FIREBASE_PROJECT_ID matches your Firebase Console project ID.");
      console.error("2. If you are using your own Firebase project, NEXT_PUBLIC_FIREBASE_DATABASE_ID should likely be '(default)'.");
      console.error("3. If you are using the AI Studio project, ensure the Database ID matches exactly.");
      console.error("4. Ensure Firestore is enabled in the Firebase Console for this project.");
      console.error("5. Check if your API Key has the correct restrictions for Firestore.");
    } else {
      console.error("Firestore connection test failed with error:", error);
    }
  }
}
testConnection();

export { app, auth, db, storage, rtdb };
